server:
  port: "8088"

db:
  host: "127.0.0.1"
  port: 13316
  database: "go_blog"
  username: "root"
  password: "root"

redis:
  addr: "127.0.0.1:6379"

kafka:
  addr: "localhost:9094"

grpc:
  client:
    inter:
      addr: "etcd:///service/interactive"
      threshold: 100

